First pass at try_except
